package com.saket.first100Euler;

public class Problem2 {

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */
	public static void main(String[] args) {
		long first = 1;
		long second = 2;
		
		long total = 2;

		long next;
		
		do{
			next = first+second;		
			
			if(next%2==0){
				total = total + next;
			}
			
			first = second;
			second = next;
			
		}while(next<4000000);
		System.out.println("The total is " + total);
	}
}
